pod 'Spark-SDK', :path => '../spark-sdk-ios'
pod 'SparkSetup', :path => '../spark-setup-ios'
pod 'MBProgressHUD'
pod 'TSMessages'
pod 'PullToRefreshCoreText', '~> 0.1'
pod 'ASValueTrackingSlider'
pod 'Analytics/Mixpanel'